### ISSUE TITLE
Controlling 16-segment displays?

### ISSUE THREAD

**Issue by lain-d** [LuckyResistor/LRAS1130#3]
Hi there! this Chip looks great, would love to try it. I'm looking to run 120 16-character display digits (1920 LEDs total)

Does this library allow chaining of AS1130? Is it possible to control more than one?  I would need to chain 15 total.

I think I can just write a few modifications on the library to control the characters then by LED number.

**Comment by LuckyResistor** [comment]
The library has a high-level and low-level API to access the chip. Therefore you should be able to access the chip in any possible way. Also you can set the chip address for each instance of the library, to address any number of chips on the same I2C bus.

Also the library is licensed under the GNU Lesser General Public License, make sure you read the details of this license. The source code should be simple to read and understand, so feel free to make any modifications for your project.

I suggest, instead of modifying this driver class, simple write a wrapper (high level API) around it, to keep things simple and flexible.
